server:
  port: 8086
  servlet:
    context-path: /biz-order

spring:
  application:
    name: biz-order
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.56:8848
        namespace: c0077cb0-e4fc-434c-aed5-5672b64b2993
      config:
        server-addr: 192.168.1.56:8848
        namespace: c0077cb0-e4fc-434c-aed5-5672b64b2993
        file-extension: yml
        shared-dataids: application-redis,auth-server